LIBNAMES=atmosphere common
STATICLIBS=$(foreach f,$(LIBNAMES),../../lib/lib$(f).a)

GSL_LIBNAMES=gsl gslcblas
GSL_LIBS=$(foreach d,$(GSL_LIBNAMES),-l$(d))

# Set up the build order
SUBDIRS= common atmosphere
#SUBDIRS += WModes_2


# the following provides CCPPFLAGS, CLINKER, CC_INCLUDES, SLEPC_INCLUDE, SLEPC_LIB
include ${SLEPC_DIR}/conf/slepc_common

PETC_SLEPC_INCLUDES = ${CCPPFLAGS}

export CXX=$(PETSC_DIR)/$(PETSC_ARCH_COMPLEX)/bin/mpic++

INCPATHS=$(foreach d,$(SUBDIRS),-I../$(d)) -I/usr/include ${PETC_SLEPC_INCLUDES}

export CXXFLAGS=-fpic -c -g -Wall $(INCPATHS) -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas
export LDFLAGS=-L/usr/lib

SOURCES=$(wildcard *.cpp) 
OBJECTS=$(SOURCES:.cpp=.o)

.PHONY: clean

# link	
WMod: WMod_main.o SolveWMod.o ProcessOptionsNB.o WMod_lib.o
	${CXX} $(LDFLAGS) -o $@ $^  $(STATICLIBS) $(GSL_LIBS) ${SLEPC_LIB}
	cp $@ ../../bin
	
# compile 
%.o: %.cpp
	${CXX} $(CXXFLAGS) -o $@ $< 		
	
# cleanup 
clean::
	@echo SOURCES = ${SOURCES}
	@echo OBJECTS = ${OBJECTS}
	rm -rf ${OBJECTS} WMod

