#!/bin/bash

# perform comparisons of columns 2-4 of tloss_rd_1d.nm
for i in 2 3 4 ; do
	badcols=$(./coldiff ModessRD1WCM/tloss_rd_1d.nm results/ModessRD1WCM/tloss_rd_1d.nm $i 0.99 | wc -l)
	if [ $badcols -ne 0 ] ; then
		echo "Column $i of ModessRD1WCM test FAILED"
		exit 1
	else
		echo "Column $i of ModessRD1WCM test OK"
	fi
done

