LIBNAMES=atmosphere common
STATICLIBS=$(foreach f,$(LIBNAMES),../../lib/lib$(f).a)

GSL_LIBNAMES=gsl gslcblas
GSL_LIBS=$(foreach d,$(GSL_LIBNAMES),-l$(d))

# Set up the build order
SUBDIRS= common atmosphere

# the following provides CCPPFLAGS, CLINKER, CC_INCLUDES, SLEPC_INCLUDE, SLEPC_LIB
include ${SLEPC_DIR}/conf/slepc_common

PETC_SLEPC_INCLUDES = ${CCPPFLAGS}

#CXX=$(PETSC_DIR)/$(PETSC_ARCH_COMPLEX)/bin/mpic++
CXX=g++

INCPATHS=$(foreach d,$(SUBDIRS),-I../$(d)) -I/usr/include ${PETC_SLEPC_INCLUDES}

CXXFLAGS=-fpic -c -g -Wall $(INCPATHS) -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas
#LDFLAGS=-L/usr/lib -L$(PETSC_DIR)/$(PETSC_ARCH_COMPLEX)/lib
LDFLAGS=-L/usr/lib

SOURCES=$(wildcard *.cpp) 
OBJECTS=$(SOURCES:.cpp=.o)

# link	
Modess: Modess_main.o SolveModNB.o ProcessOptionsNB.o Modess_lib.o
	$(CXX) $(LDFLAGS) -o $@ $^  $(STATICLIBS) $(GSL_LIBS) $(SLEPC_LIB)
	cp $@ ../../bin
	
# compile 
%.o: %.cpp
	${CXX} $(CXXFLAGS) -o $@ $<

clean::
	-rm -rf $(OBJECTS) Modess

.PHONY: clean

