CXX=g++
CFLAGS=-c -Wall
LFLAGS=-lgsl  -lgslcblas

SUBDIRS= common atmosphere
INCPATHS=$(foreach d,$(SUBDIRS),-I../$(d))

LIBNAMES=atmosphere common
STATICLIBS=$(foreach f,$(LIBNAMES), ../../lib/lib$(f).a)

all: pape

.PHONY: clean

# link
#pape: binaryreader.o atmlib.o anyoption.o ProcessOptionsPE.o pe_main.o
#	$(CXX) binaryreader.o atmlib.o anyoption.o ProcessOptionsPE.o pe_main.o $(LFLAGS) $(STATICLIBS) -o pape
#	cp pape ../bin

pape: binaryreader.o atmlib.o ProcessOptionsPE.o pe_main.o
	$(CXX) binaryreader.o atmlib.o ProcessOptionsPE.o pe_main.o $(LFLAGS) $(STATICLIBS) -o pape
	cp pape ../../bin		

%.o: %.cpp
	$(CXX) $(CFLAGS) ${INCPATHS} -o $@ $<


#atmlib.o: atmlib.cpp
#	$(CXX) $(CFLAGS) ${INCPATHS} atmlib.cpp
	
#ProcessOptionsPE.o: ProcessOptionsPE.cpp
#	$(CXX) $(CFLAGS) ${INCPATHS} ProcessOptionsPE.cpp

#pe_main.o: pe_main.cpp
#	$(CXX) $(CFLAGS) ${INCPATHS} pe_main.cpp
	

#binaryreader.o: binaryreader.cpp
#	$(CXX) $(CFLAGS) ${INCPATHS} binaryreader.cpp
	
#anyoption.o: anyoption.cpp
#	$(CXX) $(CFLAGS) ${INCPATHS} anyoption.cpp	
	
#SampledProfile.o: SampledProfile.cpp
#	$(CXX) $(CFLAGS) ${INCPATHS} SampledProfile.cpp	
	

	
clean::
	-rm -rf *.o pape
