TYPE=static
NAME=common
VERSION=.1.1.0

EXTENSIONS=cpp c f90 f77 f
ALL=$(TARGET)

SOURCES=$(wildcard *.cpp)
OBJECTS=$(SOURCES:.cpp=.o)

# Set default values for compiler and flags
TARGET=lib$(NAME).a
LINKCOMMAND=ar curv 

.PHONY: clean tidy install

all: $(TARGET)

$(TARGET): $(OBJECTS)
	ar curv $@ $^
	cp $@ ../../lib

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

clean:
	rm -rf *.o $(TARGET) $(OBJECTS)


tidy:
	rm -rf *.o
