function createfigure1(X1, Y1, Z1, X2, Y2, Z2, X3, YMatrix1)
%CREATEFIGURE(X1,Y1,Z1,X2,Y2,Z2,X3,YMATRIX1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data
%  X2:  vector of x data
%  Y2:  vector of y data
%  Z2:  vector of z data
%  X3:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 25-Sep-2015 12:57:46

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0677395 0.114237 0.351801 0.748051]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1 1]);
view(axes1,[322.5 30]);
grid(axes1,'on');
hold(axes1,'all');

% Create plot3
plot3(X1,Y1,Z1,'Parent',axes1,'Color',[1 0 0]);

% Create plot3
plot3(X2,Y2,Z2,'Parent',axes1,'Marker','.','LineStyle','none',...
    'Color',[0 0 1]);

% Create xlabel
xlabel('x [km]');

% Create ylabel
ylabel('y [km]');

% Create zlabel
zlabel('z [km]');

% Create title
title('Eigenray path with markers for the waterfall plot');

% Create axes
axes2 = axes('Parent',figure1,'Position',[0.495211 0.11 0.482759 0.724746]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[-39.7619047619047 40.3968253968254]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-21.7982456140351 2.41228070175439]);
hold(axes2,'all');

% Create multiple lines using matrix input to plot
plot(X3,YMatrix1,'Parent',axes2);

% Create text
text('Parent',axes2,'String','3.0 sec; z = 0.3 km',...
    'Position',[-40 0.506272690737663 0]);

% Create text
text('Parent',axes2,'String','64.4 sec; z = 8.4 km',...
    'Position',[-40 -0.486651516586292 0]);

% Create text
text('Parent',axes2,'String','130.1 sec; z = 18.9 km',...
    'Position',[-40 -1.53137464464846 0]);

% Create text
text('Parent',axes2,'String','198.4 sec; z = 30.4 km',...
    'Position',[-40 -2.53090826874282 0]);

% Create text
text('Parent',axes2,'String','266.0 sec; z = 41.9 km',...
    'Position',[-40 -3.48735821277212 0]);

% Create text
text('Parent',axes2,'String','333.5 sec; z = 54.2 km',...
    'Position',[-40 -4.54621089014573 0]);

% Create text
text('Parent',axes2,'String','402.4 sec; z = 67.5 km',...
    'Position',[-40 -5.48549141251819 0]);

% Create text
text('Parent',axes2,'String','473.2 sec; z = 80.7 km',...
    'Position',[-40 -6.4865781425018 0]);

% Create text
text('Parent',axes2,'String','550.8 sec; z = 94.7 km',...
    'Position',[-40 -7.50008577040288 0]);

% Create text
text('Parent',axes2,'String','623.3 sec; z = 107.3 km',...
    'Position',[-40 -8.49997041378161 0]);

% Create text
text('Parent',axes2,'String','683.8 sec; z = 114.7 km',...
    'Position',[-40 -9.50000194605801 0]);

% Create text
text('Parent',axes2,'String','739.9 sec; z = 115.4 km',...
    'Position',[-40 -10.4999988571336 0]);

% Create text
text('Parent',axes2,'String','798.8 sec; z = 109.5 km',...
    'Position',[-40 -11.5083196550596 0]);

% Create text
text('Parent',axes2,'String','868.5 sec; z = 97.7 km',...
    'Position',[-40 -12.4918444878532 0]);

% Create text
text('Parent',axes2,'String','946.7 sec; z = 83.6 km',...
    'Position',[-40 -13.4901822449812 0]);

% Create text
text('Parent',axes2,'String','1018.7 sec; z = 70.3 km',...
    'Position',[-40 -14.4900133891213 0]);

% Create text
text('Parent',axes2,'String','1087.8 sec; z = 57.0 km',...
    'Position',[-40 -15.4899615356384 0]);

% Create text
text('Parent',axes2,'String','1155.7 sec; z = 44.4 km',...
    'Position',[-40 -16.4899516753864 0]);

% Create text
text('Parent',axes2,'String','1223.1 sec; z = 32.9 km',...
    'Position',[-40 -17.4898464398089 0]);

% Create text
text('Parent',axes2,'String','1291.4 sec; z = 21.3 km',...
    'Position',[-40 -18.4896501343058 0]);

% Create text
text('Parent',axes2,'String','1358.0 sec; z = 10.5 km',...
    'Position',[-40 -19.489481464855 0]);

% Create text
text('Parent',axes2,'String','1420.2 sec; z = 1.8 km',...
    'Position',[-40 -20.4894643145096 0]);

% Create xlabel
xlabel('Reduced time [s]');

% Create title
title('Waterfall of (scaled) waveform evolution along the eigenray path');

